ALTER TABLE "Feature" ADD COLUMN "visualType" TEXT NOT NULL DEFAULT 'icon';
ALTER TABLE "Feature" ADD COLUMN "visualImage" TEXT;
ALTER TABLE "Feature" ADD COLUMN "visualAccent" TEXT DEFAULT '#B87333';
